version: '3.8'

services:
  mysql:
    build: .
    container_name: smart_oltp_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sales
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
